pipeline { 
    agent any 

    environment { 
        AWS_ACCOUNT_ID = '420905172627' 
        AWS_REGION     = 'us-east-1' 
        IMAGE_NAME     = 'shopeasy' 
        IMAGE_TAG      = "${BUILD_NUMBER}" 
        ECR_URI        = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}" 
        S3_BUCKET      = 'shopeasy-frontend-static-siddhesh' 
        
        // RDS Details 
        DB_ENDPOINT    = 'shopeasy-db.cg38ggqq8x6r.us-east-1.rds.amazonaws.com' 
        DB_USERNAME    = 'admin' 
        DB_PASSWORD    = 'shopeasy_password_123' 
        
        // App Server Details 
        ASG_NAME       = 'shopeasy-asg'
        AWS_REGION     = 'us-east-1'
    } 

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/siddheshsomvanshi1/shopeasy-devops.git'
            }
        }

        stage('Build Frontend') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }

        stage('Deploy Frontend to S3') {
            steps {
                sh "aws s3 sync frontend/build/ s3://${S3_BUCKET} --delete"
            }
        }

        stage('Invalidate CloudFront') {
            steps {
                script {
                    def DISTRIBUTION_ID = 'ENBKJVY3R087Z'
                    sh "aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths '/*'"
                }
            }
        }

        stage('Build & Push Backend') {
            steps {
                dir('app') {
                    sh 'mvn clean package -DskipTests'
                }
                sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} -f docker/Dockerfile ."
                sh "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
                sh "docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${ECR_URI}:${IMAGE_TAG}"
                sh "docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${ECR_URI}:latest"
                sh "docker push ${ECR_URI}:${IMAGE_TAG}"
                sh "docker push ${ECR_URI}:latest"
            }
        }

        stage('Deploy Backend to ASG') {
            steps {
                script {
                    // Trigger ASG Instance Refresh for Zero-Downtime Deployment
                    sh "aws autoscaling start-instance-refresh --auto-scaling-group-name ${ASG_NAME} --preferences 'MinHealthyPercentage=50'"
                    echo "Deployment to ASG ${ASG_NAME} initiated successfully."
                }
            } 
        }
    }
}